import 'package:flutter/material.dart';
import '../models/activity_model.dart';
import '../services/activity_service.dart';

import 'package:intl/intl.dart';

class AddActivityScreen extends StatefulWidget {
  const AddActivityScreen({super.key});

  @override
  State<AddActivityScreen> createState() => _AddActivityScreenState();
}

class _AddActivityScreenState extends State<AddActivityScreen> {
  final _formKey = GlobalKey<FormState>();
  final ActivityService _activityService = ActivityService();

  // Form Controllers & Status
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _descController = TextEditingController();
  
  String _selectedDuration = "5 min";
  String _selectedEnergy = "Medium";
  String _selectedLocation = "Home";
  DateTime _selectedDate = DateTime.now();

  bool _isLoading = false;

  final List<String> _durations = ["5 min", "15 min", "30 min", "60 min"];
  final List<String> _energyLevels = ["Low", "Medium", "High"];
  final List<String> _locations = ["Home", "Outside"];

  Future<void> _pickDate() async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime.now(),
      lastDate: DateTime(2030),
    );
    if (picked != null && picked != _selectedDate) {
      setState(() {
        _selectedDate = picked;
      });
    }
  }

  Future<void> _saveActivity() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isLoading = true);

      // Create new activity object (ID will be auto-generated by Firestore, so we pass empty for now or handle in Service)
      // Actually my Activity model requires ID. Firestore 'add' generates ID. 
      // The ActivityModel.toMap excludes ID usually, but my model includes it. 
      // I'll create the object locally, but since I am using .add() in service which returns a DocumentReference,
      // I don't need to pass the ID to the map.
      // Wait, let's check my ActivityService.addActivity. It calls .add(activity.toMap()).
      // My toMap() method sends everything.
      // For creation, I can send an empty string for ID, as Firestore will assign one to the DOCUMENT, 
      // but the data field 'id' might be confusing. 
      // Better approach: Firestore generates the ID.
      // Current Service: _activityCollection.add(activity.toMap());
      // Current Model: all fields required.
      // I will pass an empty string for ID.
      
      final newActivity = Activity(
        id: "", // ID is not needed for creation payload if we rely on doc ID
        title: _titleController.text.trim(),
        description: _descController.text.trim(),
        duration: _selectedDuration,
        energyLevel: _selectedEnergy,
        location: _selectedLocation,
        date: _selectedDate,
      );

      try {
        await _activityService.addActivity(newActivity).timeout(
          const Duration(seconds: 10),
          onTimeout: () {
             throw Exception("Operation timed out. Please check your internet connection or Firestore rules.");
          },
        );
        if(!mounted) return;
        Navigator.pop(context); // Go back to list
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Activity added successfully!")),
        );
      } catch (e) {
         if(!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text("Error: $e"),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 5),
          ),
        );
      } finally {
        if(mounted) setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFD5CFC7),
      appBar: AppBar(
        title: const Text("Add New Activity"),
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              // Title
              TextFormField(
                controller: _titleController,
                decoration: InputDecoration(
                  labelText: "Activity Title",
                  filled: true,
                  fillColor: Colors.white,
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                ),
                validator: (value) => value == null || value.isEmpty ? "Please enter a title" : null,
              ),
              const SizedBox(height: 16),

              // Description
              TextFormField(
                controller: _descController,
                decoration: InputDecoration(
                  labelText: "Description",
                  filled: true,
                  fillColor: Colors.white,
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                ),
                maxLines: 3,
                validator: (value) => value == null || value.isEmpty ? "Please enter a description" : null,
              ),
              const SizedBox(height: 16),

              // Duration Dropdown
              _buildDropdown("Duration", _durations, _selectedDuration, (val) {
                setState(() => _selectedDuration = val!);
              }),
              const SizedBox(height: 16),

              // Energy Dropdown
              _buildDropdown("Energy Level", _energyLevels, _selectedEnergy, (val) {
                setState(() => _selectedEnergy = val!);
              }),
              const SizedBox(height: 16),

              // Location Dropdown
              _buildDropdown("Location", _locations, _selectedLocation, (val) {
                setState(() => _selectedLocation = val!);
              }),
              // Date Picker UI
              const SizedBox(height: 16),
              const Text("Date", style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              Row(
                children: [
                   Icon(Icons.calendar_today, size: 20, color: Colors.grey[700]), // Use default Icon for now
                   const SizedBox(width: 10),
                   Text(
                    DateFormat('dd/MM/yyyy').format(_selectedDate), // Formatted date
                    style: const TextStyle(fontSize: 16),
                   ),
                   const Spacer(),
                   TextButton(
                     onPressed: _pickDate,
                     child: const Text("Change Date"),
                   ),
                ],
              ),
              const SizedBox(height: 16),

              const SizedBox(height: 24),

              // Save Button
              ElevatedButton(
                onPressed: _isLoading ? null : _saveActivity,
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.black,
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                ),
                child: _isLoading
                    ? const CircularProgressIndicator(color: Colors.white)
                    : const Text("Save Activity", style: TextStyle(fontSize: 18, color: Colors.white)),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildDropdown(String label, List<String> items, String currentValue, ValueChanged<String?> onChanged) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
        const SizedBox(height: 8),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 12),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: Colors.grey),
          ),
          child: DropdownButtonHideUnderline(
            child: DropdownButton<String>(
              value: currentValue,
              isExpanded: true,
              items: items.map((e) => DropdownMenuItem(value: e, child: Text(e))).toList(),
              onChanged: onChanged,
            ),
          ),
        ),
      ],
    );
  }
}
