// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7MTpnfpPO5ORdf9QiGRBVarrl3vHwP3Q',
    appId: '1:535158909140:web:6e269512140d1e070a3341',
    messagingSenderId: '535158909140',
    projectId: 'what-should-i-do-now-1c72f',
    authDomain: 'what-should-i-do-now-1c72f.firebaseapp.com',
    storageBucket: 'what-should-i-do-now-1c72f.firebasestorage.app',
    measurementId: 'G-6G885KVG9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3GvFNvO7wBkxpqSCSvAXrdyV-KvJtBAw',
    appId: '1:535158909140:android:e297e9ef895f29310a3341',
    messagingSenderId: '535158909140',
    projectId: 'what-should-i-do-now-1c72f',
    storageBucket: 'what-should-i-do-now-1c72f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDniAwu0M5R3NB7t0BTb5RGni1f4pz0xiY',
    appId: '1:535158909140:ios:1e96e8d737ac14770a3341',
    messagingSenderId: '535158909140',
    projectId: 'what-should-i-do-now-1c72f',
    storageBucket: 'what-should-i-do-now-1c72f.firebasestorage.app',
    iosClientId: '535158909140-r1u4l23fp783c6v5ljjohmuspe519p4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatShouldIDoNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDniAwu0M5R3NB7t0BTb5RGni1f4pz0xiY',
    appId: '1:535158909140:ios:1e96e8d737ac14770a3341',
    messagingSenderId: '535158909140',
    projectId: 'what-should-i-do-now-1c72f',
    storageBucket: 'what-should-i-do-now-1c72f.firebasestorage.app',
    iosClientId: '535158909140-r1u4l23fp783c6v5ljjohmuspe519p4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatShouldIDoNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7MTpnfpPO5ORdf9QiGRBVarrl3vHwP3Q',
    appId: '1:535158909140:web:572d121fd82859950a3341',
    messagingSenderId: '535158909140',
    projectId: 'what-should-i-do-now-1c72f',
    authDomain: 'what-should-i-do-now-1c72f.firebaseapp.com',
    storageBucket: 'what-should-i-do-now-1c72f.firebasestorage.app',
    measurementId: 'G-VP722JW28Y',
  );
}
